### ISSUE TITLE
Errors in concurrent SyncedPublisher

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/exn-middleware#7]
Components using EXN middleware library (Java at least) have problems when sharing a single instance of the connector between multiple threads, and these threads using `SyncedPublisher` to make requests that happen concurrently (request B being issued before a previous request A got a response). 
In such scenarios, request A might get the response that was intended for request B, or not receive any response at all.

**Comment by fotisp** [comment]
A solution of this issues was provided in terms of best practices when using the library for asynchronous communication.
